CREATE DATABASE IF NOT EXISTS campus_platform DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE campus_platform;


CREATE TABLE sys_user (id BIGINT PRIMARY KEY AUTO_INCREMENT, username VARCHAR(50) NOT NULL UNIQUE, password_hash VARCHAR(100) NOT NULL, nickname VARCHAR(50) NOT NULL, phone VARCHAR(20), credit_score DECIMAL(3,2) NULL DEFAULT NULL, completed_trades INT NOT NULL DEFAULT 0, role ENUM('USER','ADMIN') NOT NULL DEFAULT 'USER', status ENUM('NORMAL','DISABLED') NOT NULL DEFAULT 'NORMAL', created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE goods_category (id BIGINT PRIMARY KEY AUTO_INCREMENT, name VARCHAR(50) NOT NULL UNIQUE, sort_no INT NOT NULL DEFAULT 0);
CREATE TABLE goods (id BIGINT PRIMARY KEY AUTO_INCREMENT, seller_id BIGINT NOT NULL, category_id BIGINT NOT NULL, title VARCHAR(100) NOT NULL, description TEXT NOT NULL, price DECIMAL(10,2) NOT NULL DEFAULT 0, original_price DECIMAL(10,2), trade_location VARCHAR(100) NOT NULL DEFAULT '', view_count BIGINT NOT NULL DEFAULT 0, condition_level VARCHAR(30) NOT NULL, delivery_mode ENUM('SELF_PICKUP','DORM_DELIVERY') NOT NULL DEFAULT 'SELF_PICKUP', delivery_note VARCHAR(100), bargaining_allowed BOOLEAN NOT NULL DEFAULT TRUE, image_url VARCHAR(500), audit_status ENUM('PENDING','APPROVED','REJECTED') NOT NULL DEFAULT 'PENDING', trade_status ENUM('ON_SALE','RESERVED','SOLD','OFF_SHELF') NOT NULL DEFAULT 'ON_SALE', created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY (seller_id) REFERENCES sys_user(id), FOREIGN KEY (category_id) REFERENCES goods_category(id));
CREATE TABLE lost_found (id BIGINT PRIMARY KEY AUTO_INCREMENT, publisher_id BIGINT NOT NULL, type ENUM('LOST','FOUND') NOT NULL, title VARCHAR(100) NOT NULL, description TEXT NOT NULL, location VARCHAR(100) NOT NULL, audit_status ENUM('PENDING','APPROVED','REJECTED') NOT NULL DEFAULT 'PENDING', status ENUM('OPEN','RESOLVED','CLOSED') NOT NULL DEFAULT 'OPEN', created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY (publisher_id) REFERENCES sys_user(id));
CREATE TABLE favorite (id BIGINT PRIMARY KEY AUTO_INCREMENT, user_id BIGINT NOT NULL, goods_id BIGINT NOT NULL, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE KEY uk_favorite (user_id, goods_id), FOREIGN KEY (user_id) REFERENCES sys_user(id), FOREIGN KEY (goods_id) REFERENCES goods(id));
CREATE TABLE order_intention (id BIGINT PRIMARY KEY AUTO_INCREMENT, buyer_id BIGINT NOT NULL, goods_id BIGINT NOT NULL, message VARCHAR(255), status ENUM('PENDING','ACCEPTED','REJECTED','CANCELLED','COMPLETED') NOT NULL DEFAULT 'PENDING', created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY (buyer_id) REFERENCES sys_user(id), FOREIGN KEY (goods_id) REFERENCES goods(id));
CREATE TABLE seller_review (id BIGINT PRIMARY KEY AUTO_INCREMENT, order_id BIGINT NOT NULL UNIQUE, rating TINYINT NOT NULL, content VARCHAR(255) NOT NULL DEFAULT '', created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT chk_seller_rating CHECK (rating BETWEEN 1 AND 5), FOREIGN KEY (order_id) REFERENCES order_intention(id));
CREATE TABLE report (id BIGINT PRIMARY KEY AUTO_INCREMENT, reporter_id BIGINT NOT NULL, goods_id BIGINT, lost_found_id BIGINT, reason VARCHAR(255) NOT NULL, status ENUM('PENDING','PROCESSED','REJECTED') NOT NULL DEFAULT 'PENDING', created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY (reporter_id) REFERENCES sys_user(id), FOREIGN KEY (goods_id) REFERENCES goods(id), FOREIGN KEY (lost_found_id) REFERENCES lost_found(id));
INSERT INTO goods_category(name, sort_no) VALUES ('教材资料',1),('数码产品',2),('生活用品',3),('运动器材',4),('其他',5),('服饰鞋包',6),('美妆个护',7),('家用电器',8),('出行工具',9),('乐器文娱',10),('手作周边',11);
CREATE TABLE IF NOT EXISTS media_asset (
 id VARCHAR(36) PRIMARY KEY, owner_id BIGINT NOT NULL, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY(owner_id) REFERENCES sys_user(id)
);
CREATE TABLE IF NOT EXISTS goods_image (
 goods_id BIGINT NOT NULL, media_id VARCHAR(36) NOT NULL, sort_no INT NOT NULL,
 PRIMARY KEY(goods_id,media_id), FOREIGN KEY(goods_id) REFERENCES goods(id), FOREIGN KEY(media_id) REFERENCES media_asset(id)
);
CREATE TABLE IF NOT EXISTS service_fee (
 order_id BIGINT PRIMARY KEY, amount DECIMAL(10,2) NOT NULL, fee DECIMAL(10,2) NOT NULL,
 status ENUM('UNPAID','PENDING','CONFIRMED','SETTLED','REJECTED','REFUND_PENDING','REFUNDED','CANCELLED') NOT NULL DEFAULT 'UNPAID',
 payer_reference VARCHAR(100), proof MEDIUMBLOB, verified_reference VARCHAR(100) UNIQUE,
 verified_by BIGINT, verified_at DATETIME, note VARCHAR(255), refund_reference VARCHAR(100) UNIQUE,
 created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 CHECK(amount>=0 AND fee>=0 AND fee<=amount), FOREIGN KEY(order_id) REFERENCES order_intention(id)
);
CREATE TABLE IF NOT EXISTS payment_setting (
 id INT PRIMARY KEY, qr_url VARCHAR(100), payee_name VARCHAR(80), instructions VARCHAR(255)
);
INSERT IGNORE INTO payment_setting(id) VALUES(1);
CREATE TABLE chat_conversation (
 id BIGINT PRIMARY KEY AUTO_INCREMENT, user_low BIGINT NOT NULL, user_high BIGINT NOT NULL,
 low_read_id BIGINT NOT NULL DEFAULT 0, high_read_id BIGINT NOT NULL DEFAULT 0,
 updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 UNIQUE KEY uk_chat_pair(user_low,user_high), CHECK(user_low<user_high),
 FOREIGN KEY(user_low) REFERENCES sys_user(id), FOREIGN KEY(user_high) REFERENCES sys_user(id)
);
CREATE TABLE chat_message (
 id BIGINT PRIMARY KEY AUTO_INCREMENT, conversation_id BIGINT NOT NULL, sender_id BIGINT NOT NULL,
 content VARCHAR(2000) NOT NULL, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 KEY ix_chat_history(conversation_id,id), FOREIGN KEY(conversation_id) REFERENCES chat_conversation(id),
 FOREIGN KEY(sender_id) REFERENCES sys_user(id)
);


