package com.campus.platform.controller;
import com.campus.platform.common.*; import com.campus.platform.repository.PlatformRepository; import jakarta.servlet.http.*; import jakarta.validation.Valid; import org.springframework.http.*; import org.springframework.web.bind.annotation.*;
import org.springframework.web.server.ResponseStatusException;

import java.util.*;
@RestController @RequestMapping("/api") @CrossOrigin public class BusinessController { private final PlatformRepository repo; public BusinessController(PlatformRepository repo){this.repo=repo;} private io.jsonwebtoken.Claims claims(HttpServletRequest request){return (io.jsonwebtoken.Claims)request.getAttribute("CURRENT_USER");} private long uid(HttpServletRequest request){return ((Number)claims(request).get("uid")).longValue();} private void admin(HttpServletRequest request){if(!"ADMIN".equals(claims(request).get("role"))) throw new ResponseStatusException(HttpStatus.FORBIDDEN,"需要管理员权限");}
@GetMapping("/categories") List<Map<String,Object>> categories(){return repo.categories();}
@GetMapping("/me/goods") List<Map<String,Object>> mine(HttpServletRequest http){return repo.mine(uid(http),false);}
@GetMapping("/me/favorites") List<Map<String,Object>> favorites(HttpServletRequest http){return repo.mine(uid(http),true);}
@PutMapping("/me/favorites/{id}") Map<String,String> favorite(@PathVariable long id,HttpServletRequest http){repo.favorite(uid(http),id,true);return Map.of("message","已收藏");}
@DeleteMapping("/me/favorites/{id}") Map<String,String> unfavorite(@PathVariable long id,HttpServletRequest http){repo.favorite(uid(http),id,false);return Map.of("message","已取消收藏");}
@PostMapping("/goods/{id}/views") Map<String,Object> view(@PathVariable long id){return repo.view(id);}
@GetMapping("/goods") List<Map<String,Object>> goods(){return repo.goods();}
@PostMapping("/goods") ResponseEntity<?> addGoods(@Valid @RequestBody GoodsRequest request,HttpServletRequest http){String delivery="DORM_DELIVERY".equals(request.deliveryMode())?"DORM_DELIVERY":"SELF_PICKUP";boolean bargaining=request.bargainingAllowed()==null||request.bargainingAllowed();Map<String,Object> values=new HashMap<>(Map.of("categoryId",request.categoryId(),"title",request.title(),"description",request.description(),"price",request.price(),"condition",request.condition(),"deliveryMode",delivery,"deliveryNote",request.deliveryNote()==null?"":request.deliveryNote(),"bargainingAllowed",bargaining));values.put("originalPrice",request.originalPrice());values.put("tradeLocation",request.tradeLocation()==null?"":request.tradeLocation());long id=repo.addGoods(uid(http),values,request.images());return ResponseEntity.ok(Map.of("id",id,"message","已提交审核"));}
@GetMapping("/lost-found") List<Map<String,Object>> lost(@RequestParam(defaultValue="") String keyword){return repo.lost(keyword);}
@PostMapping("/lost-found") ResponseEntity<?> addLost(@Valid @RequestBody LostFoundRequest request,HttpServletRequest http){repo.addLost(uid(http),Map.of("type",request.type(),"title",request.title(),"description",request.description(),"location",request.location()));return ResponseEntity.ok(Map.of("message","已提交审核"));}
@PostMapping("/orders/intentions") ResponseEntity<?> order(@Valid @RequestBody OrderRequest request,HttpServletRequest http){repo.intention(uid(http),Map.of("goodsId",request.goodsId(),"message",request.message()==null?"":request.message()));return ResponseEntity.ok(Map.of("message","购买意向已提交"));}
@GetMapping("/admin/audits") List<Map<String,Object>> audits(HttpServletRequest http){admin(http);return repo.audits();}
@PutMapping("/admin/audits/{type}/{id}") ResponseEntity<?> audit(@PathVariable String type,@PathVariable long id,@RequestParam String status,HttpServletRequest http){admin(http);if(!Set.of("APPROVED","REJECTED").contains(status)) throw new IllegalArgumentException("审核状态不合法");if(!Set.of("GOODS","LOST_FOUND").contains(type.toUpperCase())) throw new IllegalArgumentException("审核类型不合法");repo.audit(type.toUpperCase(),id,status);return ResponseEntity.ok(Map.of("message","审核完成"));}}
