USE campus_platform;

ALTER TABLE order_intention MODIFY COLUMN status ENUM('PENDING','ACCEPTED','REJECTED','CANCELLED','COMPLETED') NOT NULL DEFAULT 'PENDING';

CREATE TABLE IF NOT EXISTS seller_review (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    order_id BIGINT NOT NULL UNIQUE,
    rating TINYINT NOT NULL,
    content VARCHAR(255) NOT NULL DEFAULT '',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_seller_rating CHECK (rating BETWEEN 1 AND 5),
    FOREIGN KEY (order_id) REFERENCES order_intention(id)
);
